

#RUN apt-get update
#RUN apt-get install libnss3
#RUN apt --fix-broken -y install
##RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
##RUN sudo dpkg -i google-chrome-stable_current_amd64.deb
#
